/***
***   This file is generated by JAIG at 18:43 02.03.2024
***   As a result of parsing GPT response 
***   4_split_packages-response
***/
package com.github.valentina810.foodforeveryone.domain.order;

import java.util.Date;

public class Order {
    private Long id;
    private Long idUser;
    private Long idStatusOrder;
    private String deliveryAddress;
    private Date deliveryDate;
    private StatusOrder status;
    
    // Constructor, getters and setters
}