/***
***   This file is generated by JAIG at 21:26 02.03.2024
***   As a result of parsing GPT response 
***   5_add_repositories-response
***/
package com.github.valentina810.foodforeveryone.repository.dish;

import com.github.valentina810.foodforeveryone.domain.dish.Dish;
import org.springframework.data.jpa.repository.JpaRepository;

public interface DishRepository extends JpaRepository<Dish, Long> {
}