/***
 ***   This file is generated by JAIG at 23:55 03.03.2024
 ***   As a result of parsing GPT response
 ***   controller-response
 ***/
package com.github.valentina810.foodforeveryone.service.order;

import com.github.valentina810.foodforeveryone.domain.order.Order;
import com.github.valentina810.foodforeveryone.dto.OrderAddDto;

public interface OrderService {
    Order addOrder(OrderAddDto order);

    Order findOrderByNumber(Long orderNumber);

    Order updateOrderStatus(Long orderId, Long statusId);
}