/***
 ***   This file is generated by JAIG at 21:12 03.03.2024
 ***   As a result of parsing GPT response
 ***   controller-response
 ***/
package com.github.valentina810.foodforeveryone.services.dish;

import com.github.valentina810.foodforeveryone.domain.dish.DishInOrder;
import com.github.valentina810.foodforeveryone.dto.DishInOrderAddDto;

import java.util.List;

public interface DishInOrderService {
    DishInOrder addDishToOrder(DishInOrderAddDto dishInOrderAddDto);

    void removeDishFromOrder(Long id);

    List<DishInOrder> getDishesByOrderId(Long orderId);
}