/***
***   This file is generated by JAIG at 22:37 03.03.2024
***   As a result of parsing GPT response 
***   controller-response
***/
package com.github.valentina810.foodforeveryone.service.donation;

import com.github.valentina810.foodforeveryone.domain.donation.Donation;
import com.github.valentina810.foodforeveryone.dto.DonationAddDto;

import java.util.List;

public interface DonationService {
    Donation addDonation(DonationAddDto donation);
    List<Donation> getDonationsByUserId(Long userId);
    Donation getDonationById(Long donationId);
}