/***
 ***   This file is generated by JAIG at 21:12 03.03.2024
 ***   As a result of parsing GPT response
 ***   controller-response
 ***/
package com.github.valentina810.foodforeveryone.controller.dish;

import com.github.valentina810.foodforeveryone.domain.dish.DishInOrder;
import com.github.valentina810.foodforeveryone.dto.DishInOrderAddDto;
import com.github.valentina810.foodforeveryone.services.dish.DishInOrderService;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import java.util.List;

@RestController
@RequestMapping("/dishInOrders")
@RequiredArgsConstructor
@Validated
public class DishInOrderController {

    private final DishInOrderService dishInOrderService;

    @PostMapping
    public DishInOrder addDishToOrder(@Valid @RequestBody DishInOrderAddDto dishInOrderAddDto) {
        return dishInOrderService.addDishToOrder(dishInOrderAddDto);
    }

    @DeleteMapping("/{id}")
    public void removeDishFromOrder(@PathVariable("id") Long id) {
        dishInOrderService.removeDishFromOrder(id);
    }

    @GetMapping("/search")
    public List<DishInOrder> getDishesByOrderId(@RequestParam("orderId") Long orderId) {
        return dishInOrderService.getDishesByOrderId(orderId);
    }
}