/***
***   This file is generated by JAIG at 18:43 02.03.2024
***   As a result of parsing GPT response 
***   4_split_packages-response
***/
package com.github.valentina810.foodforeveryone.domain.user;

public class UserType {
    private Long id;
    private String type;
    
    // Constructor, getters and setters
}