/***
***   This file is generated by JAIG at 21:50 02.03.2024
***   As a result of parsing GPT response 
***   6_add_connection_between_repositories_and_models-response
***/
package com.github.valentina810.foodforeveryone.domain.user;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

@Entity
@Table(name = "user_roles")
public class UserRole {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id_user_role", nullable = false, unique = true)
    private Long id;

    private String role;

    // getters and setters
}