/***
***   This file is generated by JAIG at 21:26 02.03.2024
***   As a result of parsing GPT response 
***   5_add_repositories-response
***/
package com.github.valentina810.foodforeveryone.repository.order;

import com.github.valentina810.foodforeveryone.domain.order.StatusOrder;
import org.springframework.data.jpa.repository.JpaRepository;

public interface StatusOrderRepository extends JpaRepository<StatusOrder, Long> {
}