/***
***   This file is generated by JAIG at 18:43 02.03.2024
***   As a result of parsing GPT response 
***   4_split_packages-response
***/
package com.github.valentina810.foodforeveryone.domain.donation;

import java.util.Date;

public class Donation {
    private Long id;
    private Long idUser;
    private Double amount;
    private Date date;
    private String paymentMethod;
    
    // Constructor, getters and setters
}