/***
***   This file is generated by JAIG at 18:43 02.03.2024
***   As a result of parsing GPT response 
***   4_split_packages-response
***/
package com.github.valentina810.foodforeveryone.domain.dish;

public class DishInOrder {
    private Long id;
    private Long idDish;
    private Long idOrder;
    private Integer count;

    // Constructor, getters and setters
}