/***
 ***   This file is generated by JAIG at 21:50 02.03.2024
 ***   As a result of parsing GPT response
 ***   6_add_connection_between_repositories_and_models-response
 ***/
package com.github.valentina810.foodforeveryone.domain.dish;

import com.github.valentina810.foodforeveryone.domain.order.Order;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

@Entity
@Table(name = "dishes_in_order")
public class DishInOrder {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id_dishes_in_order", nullable = false, unique = true)
    private Long id;

    @ManyToOne
    @JoinColumn(name = "dish_id", nullable = false)
    private Dish idDish;

    @ManyToOne
    @JoinColumn(name = "order_id", nullable = false)
    private Order idOrder;

    private Integer count;

    // getters and setters
}