/***
***   This file is generated by JAIG at 18:43 02.03.2024
***   As a result of parsing GPT response 
***   4_split_packages-response
***/
package com.github.valentina810.foodforeveryone.domain.dish;

public class Dish {
    private Long id;
    private String name;
    private String description;
    private Double price;
    private Boolean isAvailable;

    // Constructor, getters and setters
}